import Head from 'next/head';
import Navbar from '../../../components/general/Navbar';
import Footer from '../../../components/general/Footer';
import styles from '@/styles/livro/Cadastro.module.css';
import Form from '../../../components/livro/Form';

export default function Cadastro() {
    return (
        <>
            <Head>
                <title>Livraria MP</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Navbar />
            <main className={styles.main}>
                <div className={styles.container}>
                    <div className={styles.containerTitle}>
                        <h1>Tela de Cadastro de Livros</h1>
                    </div>
                    <div className={styles.containerText}>
                        <p>Cadatre seus livros aqui ou consulte-os</p>
                    </div>
                </div>
                <div className={styles.containerForm}>
                    <Form />
                </div>

                <div className={styles.containerConsultar}>
                    <div className={styles.containerConsultarTitle}>
                        <h1>Consultar Livros</h1>
                    </div>
                    <div className={styles.containerConsultarText}>
                        <p>Consulte os livros aqui.</p>
                    </div>
                    <div className={styles.containerConsultarButton}>
                        <a href="/livro/consultar">Consulte</a>
                    </div>
                </div>

            </main>
            <Footer />
        </>
    );
}