import Head from 'next/head';
import Navbar from '../../../components/general/Navbar';
import Footer from '../../../components/general/Footer';

export default function Consultar() {
    return (
        <>
            <Head>
                    <title>Livraria MP</title>
                    <meta name="description" content="Generated by create next app" />
                    <meta name="viewport" content="width=device-width, initial-scale=1" />
                    <link rel="icon" href="/favicon.ico" />
            </Head>
            <Navbar />
            <main></main>
            <Footer />
        </>
    );
}