import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Navbar from "../../components/general/Navbar";
import Footer from "../../components/general/Footer";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Livraria MP</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.containerTitle}>
          <h1>Bem-vindo!</h1>
        </div>
        <div className={styles.containerText}>
          <p>Esse é um painel administrativo onde poderá cadastrar livros e grupos de precificações</p>
        </div>
      </main>
      <Footer />
    </>
  );
}
